kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: foxbat-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30090
        hostPort: 8080
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
